# Generated by Django 2.2.18 on 2021-07-26 20:51
from django.db import migrations

from shuup import configuration


def reindex_catalog(apps, schema_editor):
    configuration.set(None, "product_catalog_needs_reindex", True)


class Migration(migrations.Migration):

    dependencies = [
        ("shuup", "0094_product_catalog"),
    ]

    operations = [migrations.RunPython(reindex_catalog, migrations.RunPython.noop)]
