# Generated by Django 2.2.24 on 2021-08-27 20:47

import enumfields.fields
from django.db import migrations, models

import shuup.core.fields
import shuup.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('shuup', '0098_change_productmedia_verbose_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcatalogprice',
            name='is_visible',
            field=models.BooleanField(db_index=True, default=True, editable=False, help_text='Whether the product is visible. This status is managed by the pricing module. The visibility can be some product attribute that disables it or even a disabled shop or supplier.', verbose_name='is visible'),
        ),
        migrations.AddField(
            model_name='productcatalogpricerule',
            name='authenticated_user',
            field=models.BooleanField(db_index=True, editable=False, help_text='Whether the product is available only for authenticated users.', null=True, verbose_name='authenticated user'),
        ),
        migrations.AlterField(
            model_name='product',
            name='mode',
            field=enumfields.fields.EnumIntegerField(db_index=True, default=0, enum=shuup.core.models.ProductMode, verbose_name='mode'),
        ),
        migrations.AlterField(
            model_name='productcatalogdiscountedprice',
            name='discounted_price_value',
            field=shuup.core.fields.MoneyValueField(db_index=True, decimal_places=9, editable=False, help_text='The indexed discounted product price.', max_digits=36, null=True, verbose_name='discounted price'),
        ),
        migrations.AlterField(
            model_name='productcatalogprice',
            name='price_value',
            field=shuup.core.fields.MoneyValueField(db_index=True, decimal_places=9, editable=False, help_text='The indexed product price', max_digits=36, verbose_name='price'),
        ),
        migrations.AddIndex(
            model_name='productcatalogprice',
            index=models.Index(fields=['shop', 'is_visible', 'is_available'], name='shuup_produ_shop_id_4e728c_idx'),
        ),
    ]
