# Generated by Django 2.2.24 on 2021-08-28 17:14

from django.db import migrations

from shuup import configuration


def reindex_product_catalog(apps, schema_editor):
    configuration.set(None, "product_catalog_needs_reindex", True)


class Migration(migrations.Migration):

    dependencies = [
        ("shuup", "0099_catalog_visible_product"),
    ]

    operations = [migrations.RunPython(reindex_product_catalog, migrations.RunPython.noop)]
