# Generated by Django 2.2.24 on 2021-09-02 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import shuup.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ("shuup", "0101_move_settings_to_db"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basket",
            name="created_on",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, help_text="Datetime of creation", verbose_name="created on"
            ),
        ),
        migrations.AlterField(
            model_name="basket",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                help_text="User ID of basket creator",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="core_baskets_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="creator",
            ),
        ),
        migrations.AlterField(
            model_name="basket",
            name="currency",
            field=shuup.core.fields.CurrencyField(
                help_text="Currency of the prices", max_length=4, verbose_name="currency"
            ),
        ),
        migrations.AlterField(
            model_name="basket",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                help_text="Customer Contact ID",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer_core_baskets",
                to="shuup.Contact",
                verbose_name="customer",
            ),
        ),
        migrations.AlterField(
            model_name="basket",
            name="deleted",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Indicates if the basket has been deleted.",
                verbose_name="deleted",
            ),
        ),
        migrations.AlterField(
            model_name="basket",
            name="finished",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Indicates if the basket purchase is completed",
                verbose_name="finished",
            ),
        ),
        migrations.AlterField(
            model_name="basket",
            name="orderer",
            field=models.ForeignKey(
                blank=True,
                help_text="Orderer Person Contact ID",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orderer_core_baskets",
                to="shuup.PersonContact",
                verbose_name="orderer",
            ),
        ),
        migrations.AlterField(
            model_name="basket",
            name="products",
            field=models.ManyToManyField(
                blank=True, help_text="Products in the basket", to="shuup.Product", verbose_name="products"
            ),
        ),
        migrations.AlterField(
            model_name="basket",
            name="shop",
            field=models.ForeignKey(
                help_text="Shop ID", on_delete=django.db.models.deletion.CASCADE, to="shuup.Shop", verbose_name="shop"
            ),
        ),
        migrations.AlterField(
            model_name="basket",
            name="taxful_total_price_value",
            field=shuup.core.fields.MoneyValueField(
                blank=True,
                decimal_places=9,
                default=0,
                help_text="Total price without including taxes",
                max_digits=36,
                null=True,
                verbose_name="taxful total price",
            ),
        ),
        migrations.AlterField(
            model_name="basket",
            name="taxless_total_price_value",
            field=shuup.core.fields.MoneyValueField(
                blank=True,
                decimal_places=9,
                default=0,
                help_text="Total price including taxes",
                max_digits=36,
                null=True,
                verbose_name="taxless total price",
            ),
        ),
        migrations.AlterField(
            model_name="basket",
            name="title",
            field=models.CharField(blank=True, help_text="Basket title", max_length=64, verbose_name="title"),
        ),
        migrations.AlterField(
            model_name="basket",
            name="updated_on",
            field=models.DateTimeField(
                auto_now=True, db_index=True, help_text="Datetime of last modification", verbose_name="updated on"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="depth",
            field=shuup.core.fields.UnitKeyField(
                decimal_places=9,
                default=0,
                help_text="Set the measured depth or length of your product or product packaging. This will provide customers with the product size and help with calculating shipping costs.",
                max_digits=36,
                unit_key="length_unit",
                verbose_name="depth ({})",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="gross_weight",
            field=shuup.core.fields.UnitKeyField(
                decimal_places=9,
                default=0,
                help_text="Set the measured gross weight of your product WITH its packaging. This will help with calculating shipping costs.",
                max_digits=36,
                unit_key="mass_unit",
                verbose_name="gross weight ({})",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="height",
            field=shuup.core.fields.UnitKeyField(
                decimal_places=9,
                default=0,
                help_text="Set the measured height of your product or product packaging. This will provide customers with the product size and help with calculating shipping costs.",
                max_digits=36,
                unit_key="length_unit",
                verbose_name="height ({})",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="net_weight",
            field=shuup.core.fields.UnitKeyField(
                decimal_places=9,
                default=0,
                help_text="Set the measured weight of your product WITHOUT its packaging. This will provide customers with the actual product's weight.",
                max_digits=36,
                unit_key="mass_unit",
                verbose_name="net weight ({})",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="width",
            field=shuup.core.fields.UnitKeyField(
                decimal_places=9,
                default=0,
                help_text="Set the measured width of your product or product packaging. This will provide customers with the product size and help with calculating shipping costs.",
                max_digits=36,
                unit_key="length_unit",
                verbose_name="width ({})",
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="volume",
            field=shuup.core.fields.UnitKeyField(
                decimal_places=9, default=0, max_digits=36, unit_key="volume_unit", verbose_name="volume ({})"
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="weight",
            field=shuup.core.fields.UnitKeyField(
                decimal_places=9, default=0, max_digits=36, unit_key="mass_unit", verbose_name="weight ({})"
            ),
        ),
        migrations.AlterField(
            model_name="shipmentproduct",
            name="unit_volume",
            field=shuup.core.fields.UnitKeyField(
                decimal_places=9, default=0, max_digits=36, unit_key="volume_unit", verbose_name="unit volume ({})"
            ),
        ),
        migrations.AlterField(
            model_name="shipmentproduct",
            name="unit_weight",
            field=shuup.core.fields.UnitKeyField(
                decimal_places=9, default=0, max_digits=36, unit_key="mass_unit", verbose_name="unit weight ({})"
            ),
        ),
        migrations.AlterField(
            model_name="shopproduct",
            name="product",
            field=shuup.core.fields.UnsavedForeignKey(
                help_text="Related product ID",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shop_products",
                to="shuup.Product",
                verbose_name="product",
            ),
        ),
        migrations.AlterField(
            model_name="weightbasedpricerange",
            name="max_value",
            field=shuup.core.fields.UnitKeyField(
                blank=True,
                decimal_places=9,
                default=0,
                help_text="The maximum weight before this price no longer applies.",
                max_digits=36,
                null=True,
                unit_key="mass_unit",
                verbose_name="max weight ({})",
            ),
        ),
        migrations.AlterField(
            model_name="weightbasedpricerange",
            name="min_value",
            field=shuup.core.fields.UnitKeyField(
                blank=True,
                decimal_places=9,
                default=0,
                help_text="The minimum weight for this price to apply.",
                max_digits=36,
                null=True,
                unit_key="mass_unit",
                verbose_name="min weight ({})",
            ),
        ),
    ]
