# Generated by Django 2.2.24 on 2021-09-09 19:08
import os
from django.conf import settings
from django.db import migrations
from django.utils.translation import gettext_lazy as _

from shuup.core.models import SMTPProtocol


def create_default_account(apps, schema_editor):
    if settings.EMAIL_HOST and settings.EMAIL_HOST_USER and settings.EMAIL_HOST_PASSWORD:
        SMTPAccount = apps.get_model("shuup.SMTPAccount")

        if settings.EMAIL_USE_TLS:
            protocol = SMTPProtocol.TLS
        elif settings.EMAIL_USE_SSL:
            protocol = SMTPProtocol.SSL
        else:
            protocol = SMTPProtocol.NotEncrypted

        certfile = None
        keyfile = None

        if settings.EMAIL_SSL_CERTFILE and os.path.exists(settings.EMAIL_SSL_CERTFILE):
            certfile = open(settings.EMAIL_SSL_CERTFILE, "r").read()

        if settings.EMAIL_SSL_KEYFILE and os.path.exists(settings.EMAIL_SSL_KEYFILE):
            keyfile = open(settings.EMAIL_SSL_KEYFILE, "r").read()

        SMTPAccount.objects.create(
            name=_("Default"),
            host=settings.EMAIL_HOST,
            port=settings.EMAIL_PORT,
            username=settings.EMAIL_HOST_USER,
            password=settings.EMAIL_HOST_PASSWORD,
            timeout=settings.EMAIL_TIMEOUT or 10,
            default_from_email=settings.DEFAULT_FROM_EMAIL,
            protocol=protocol,
            ssl_certfile=certfile,
            ssl_keyfile=keyfile,
            default_account=True,
        )


def delete_default_accounts(apps, schema_editor):
    if settings.EMAIL_HOST and settings.EMAIL_HOST_USER and settings.EMAIL_HOST_PASSWORD:
        SMTPAccount = apps.get_model("shuup.SMTPAccount")
        SMTPAccount.objects.filter(default_account=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("shuup", "0103_smtp_accounts"),
    ]

    operations = [migrations.RunPython(create_default_account, delete_default_accounts)]
