# Generated by Django 2.2.24 on 2021-10-20 11:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shuup", "0104_create_default_smtp_account"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesunit",
            name="decimals",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="The number of decimal places allowed by this sales unit.Set this to a value greater than zero if products with this sales unit can be sold in fractional quantities.",
                validators=[django.core.validators.MaxValueValidator(10)],
                verbose_name="allowed decimal places",
            ),
        ),
    ]
