FROM gcr.io/engaged-ground-343617/givesomeapp:2.10.9
RUN python -m pip install django-debug-toolbar==3.2.4
RUN python -m pip install ipdb
COPY debug_image/env ${APP_HOME}/.env
COPY debug_image/gcsfuse_run.sh ${APP_HOME}/gcsfuse_run.sh
RUN chmod +x ${APP_HOME}/gcsfuse_run.sh
COPY qa_image/nginx.conf /etc/nginx/http.d/default.conf
COPY app/ /opt/app
