# Generated by Django 2.2.16 on 2020-11-12 21:27

from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import givesome.models.vendor_extra


class Migration(migrations.Migration):

    dependencies = [
        ('shuup', '0077_remove_approved_from_supplier'),
        ('givesome', '0003_add_project_promote_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_type', enumfields.fields.EnumIntegerField(default=1, enum=givesome.models.vendor_extra.VendorExtraType, help_text='Charities may sign up as charities in order to create charity projects. Theymay pay to upgrade to Branded Vendor status if they wish, which will enablethem to feature their projects on their Branded Vendor Page.', verbose_name='vendor type')),
                ('vendor', models.OneToOneField(help_text='The vendor described by this extra information.', on_delete=django.db.models.deletion.CASCADE, to='shuup.Supplier')),
            ],
        ),
    ]
