# Generated by Django 2.2.16 on 2020-11-13 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('givesome', '0004_vendorextra'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorextra',
            name='allow_brand_page',
            field=models.BooleanField(default=True),
        ),
    ]
