# Generated by Django 2.2.16 on 2020-11-16 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('givesome', '0005_vendorextra_allow_brand_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='givesomepromotedproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promoting_suppliers', to='shuup.ShopProduct'),
        ),
    ]
