# Generated by Django 2.2.16 on 2020-11-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('givesome', '0007_add_vendor_extra_related_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorextra',
            name='website_url',
            field=models.CharField(blank=True, help_text="Enter the URL of the vendor if you would like customers to be able to visit the vendor's website.", max_length=128, null=True, verbose_name='URL'),
        ),
    ]
