# Generated by Django 2.2.16 on 2020-12-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('givesome', '0010_projectsustainabilitygoals'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorextra',
            name='color',
            field=models.CharField(blank=True, help_text="Enter the hex code of the organization's main color.", max_length=7, null=True, verbose_name='Hex color code'),
        ),
    ]
