# Generated by Django 2.2.16 on 2020-12-02 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shuup', '0077_remove_approved_from_supplier'),
        ('givesome', '0011_vendorextra_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_amount', models.IntegerField()),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project_extra', to='shuup.Product')),
            ],
        ),
    ]
