# Generated by Django 2.2.16 on 2020-12-04 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('givesome', '0013_create_vendor_information_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectextra',
            name='fully_funded_date',
            field=models.DateTimeField(blank=True, db_index=True, help_text='The date at which the project reached its funding goal.', null=True, verbose_name='Fully funded date'),
        ),
    ]
