# Generated by Django 2.2.16 on 2020-12-08 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shuup', '0079_longer_log_entry_fields'),
        ('givesome', '0014_add_funded_date_to_project_extra'),
    ]

    operations = [
        migrations.CreateModel(
            name='GivesomeOffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='name')),
                ('ordering', models.IntegerField(default=0, verbose_name='ordering')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shuup.Supplier')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OfficeSustainabilityGoals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.ManyToManyField(blank=True, related_name='office_sustainability_goals', to='givesome.SustainabilityGoal', verbose_name='offices')),
                ('office', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='office_sustainability_goals', to='givesome.GivesomeOffice')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
