# Generated by Django 2.2.17 on 2020-12-09 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shuup', '0079_longer_log_entry_fields'),
        ('givesome', '0016_delete_promoted_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='givesomeoffice',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offices', to='shuup.Supplier'),
        ),
        migrations.CreateModel(
            name='GivesomePromotedProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.IntegerField(default=0)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promoted_projects', to='givesome.GivesomeOffice')),
                ('shop_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promoting_offices', to='shuup.ShopProduct')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
