# Generated by Django 2.2.17 on 2020-12-21 12:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image
import parler.fields
import parler.models
import shuup.core.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('shuup', '0079_longer_log_entry_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('givesome', '0018_add_office_term_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='GivecardCampaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', shuup.core.fields.InternalIdentifierField(blank=True, editable=False, max_length=64, null=True, unique=True)),
                ('image', filer.fields.image.FilerImageField(blank=True, help_text='Add an image to be shown to donors when they redeem a Givecard belonging to this campaign.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image', to=settings.FILER_IMAGE_MODEL, verbose_name='image')),
                ('supplier', models.ForeignKey(blank=True, help_text='This Givecard Campaign and all givecards related to it will be available for selected vendor to be queried in reports.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='shuup.Supplier', verbose_name='branded vendor')),
            ],
            options={
                'verbose_name_plural': 'givecard campaigns',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='GivecardBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('modified_on', models.DateTimeField(auto_now=True, verbose_name='modified on')),
                ('redemption_start_date', models.DateTimeField(blank=True, help_text='The date and time the Givecard redemption starts. Givecards are not redeemable before this time.', null=True, verbose_name='Redemption start date')),
                ('redemption_end_date', models.DateTimeField(blank=True, help_text='The date and time the Givecard redemption ends. Givecards are not redeemable after this time.', null=True, verbose_name='Redemption end date')),
                ('expiration_date', models.DateTimeField(blank=True, help_text='The date and time on which the Givecard expires. After this it is no longer able to be used, and it will be hidden in donor wallets.', null=True, verbose_name='Expiration date')),
                ('amount', models.PositiveIntegerField(default=1, help_text='Amount of Givecards to generate in this batch.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100000)], verbose_name='amount')),
                ('value', models.PositiveIntegerField(help_text='Value ($) on all the Givecards generated in this batch.', verbose_name='value')),
                ('code', models.CharField(blank=True, help_text='Used for givecard redemption. Required for Multicards. This code will be the same for all Multicards in this batch.', max_length=6, null=True, verbose_name='code')),
                ('campaign', models.ForeignKey(blank=True, help_text='Related Givecard Campaign. This is required to enable Givecard redemption.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='givesome.GivecardCampaign', verbose_name='givecard batch')),
                ('office', models.ForeignKey(blank=True, help_text="Related Givecards will be restricted to only be used on this office's projects.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='givesome.GivesomeOffice', verbose_name='office')),
                ('supplier', models.ForeignKey(blank=True, help_text="Related Givecards will be restricted to only be used on this vendor's projects.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='shuup.Supplier', verbose_name='branded vendor')),
            ],
            options={
                'verbose_name_plural': 'givecard batches',
                'ordering': ('-created_on',),
            },
        ),
        migrations.CreateModel(
            name='Givecard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, help_text='Used for givecard redemption.', max_length=6, null=True, verbose_name='code')),
                ('balance', models.PositiveIntegerField(help_text='Balance ($) left on this givecard', verbose_name='value')),
                ('redeemed_on', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='redeemed on')),
                ('was_automatically_donated', models.BooleanField(default=False)),
                ('batch', models.ForeignKey(help_text='Related Givecard Campaign.', on_delete=django.db.models.deletion.CASCADE, related_name='givecards', to='givesome.GivecardBatch', verbose_name='givecard batch')),
                ('user', models.ForeignKey(blank=True, editable=False, help_text='User that has redeemed this givecard.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='givecards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GivecardCampaignTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=64)),
                ('message', models.TextField(help_text='Add a message to be shown to donors when they redeem a Givecard belonging to this campaign.', max_length=500, verbose_name='Message')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='givesome.GivecardCampaign')),
            ],
            options={
                'verbose_name': 'givecard campaign Translation',
                'db_table': 'givesome_givecardcampaign_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
