# Generated by Django 2.2.17 on 2020-12-29 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('givesome', '0019_create_givecard_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='givecardbatch',
            name='modified_on',
        ),
        migrations.AddField(
            model_name='givecardbatch',
            name='generated_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='generated on'),
        ),
        migrations.AlterField(
            model_name='givecardbatch',
            name='campaign',
            field=models.ForeignKey(blank=True, help_text='Related Givecard Campaign. This is required to enable Givecard redemption.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='givesome.GivecardCampaign', verbose_name='givecard campaign'),
        ),
    ]
