# Generated by Django 2.2.17 on 2021-01-13 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('givesome', '0021_projectextra_lives_impacted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='givecardbatch',
            name='expiration_date',
            field=models.DateField(blank=True, help_text='The date and time on which the Givecard expires. After this it is no longer able to be used, and it will be hidden in donor wallets.', null=True, verbose_name='Expiration date'),
        ),
        migrations.AlterField(
            model_name='givecardbatch',
            name='redemption_end_date',
            field=models.DateField(blank=True, help_text='The date and time the Givecard redemption ends. Givecards are not redeemable after this time.', null=True, verbose_name='Redemption end date'),
        ),
        migrations.AlterField(
            model_name='givecardbatch',
            name='redemption_start_date',
            field=models.DateField(blank=True, help_text='The date and time the Givecard redemption starts. Givecards are not redeemable before this time.', null=True, verbose_name='Redemption start date'),
        ),
    ]
