# Generated by Django 2.2.17 on 2021-01-21 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shuup', '0080_unify_tax_number_max_length'),
        ('givesome', '0022_change_datetime_fields_to_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='GivecardPaymentProcessor',
            fields=[
                ('paymentprocessor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shuup.PaymentProcessor')),
            ],
            options={
                'verbose_name': 'Givecard processor',
                'verbose_name_plural': 'Givecard processors',
            },
            bases=('shuup.paymentprocessor',),
        ),
    ]
