# Generated by Django 2.2.17 on 2021-01-27 21:13

from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import givesome.models.givecard


class Migration(migrations.Migration):

    dependencies = [
        ('givesome', '0024_completionvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='givecardbatch',
            name='expiry_type',
            field=enumfields.fields.EnumIntegerField(default=2, enum=givesome.enums.GivecardBatchExpiryType, help_text='Action taken when Givecard Batch expires. Automatic - Funds are automatically reallocated to active projects through a preset process. Manual - Funds are redirected to Givesome Purse to be manually reallocated to projects. Disabled - Funds are not reallocated to projects, but managed outside Shuup. ', verbose_name='Expiration type'),
        ),
        migrations.AddField(
            model_name='givecardbatch',
            name='restriction_type',
            field=enumfields.fields.EnumIntegerField(default=3, enum=givesome.enums.GivecardDonateRestrictionType, help_text="Defines how Givecards are allowed to be donated. Office - Givecards can only be used on this Office's branded page. Supplier - Givecards can only be used on vendor's and it's office's branded pages. Disabled - No donation restrictions.", verbose_name='Donation restriction type'),
        ),
        migrations.AlterField(
            model_name='givecardbatch',
            name='office',
            field=models.ForeignKey(blank=True, help_text="When user redeems a Givecard they will be redirected to this office's branded page. Givecards may also be restricted to this office depending on set 'Donation restriction type'", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='givesome.GivesomeOffice', verbose_name='office'),
        ),
        migrations.AlterField(
            model_name='givecardbatch',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text="When user redeems a Givecard they will be redirected to this vendor's branded page. Givecards may also be restricted to this vendor depending on set 'Donation restriction type'", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='shuup.Supplier', verbose_name='branded vendor'),
        ),
    ]
