# Generated by Django 2.2.17 on 2021-02-01 17:18

from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import givesome.models.reports


class Migration(migrations.Migration):

    dependencies = [
        ('shuup', '0082_add_name_to_shop_product'),
        ('givesome', '0025_add_batch_expiry_and_restriction_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseReportData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_type', enumfields.fields.EnumIntegerField(default=0, enum=givesome.models.reports.DonationType, verbose_name='Donation Type')),
                ('givecard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_report_data', to='givesome.Givecard')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_report_data', to='shuup.Payment', verbose_name='Payment')),
                ('promoting_brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_report_data', to='shuup.Supplier', verbose_name='Promoting Brand')),
                ('promoting_office', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_report_data', to='givesome.GivesomeOffice', verbose_name='Promoting Office')),
            ],
            options={
                'verbose_name': 'Purchase Report Data',
                'verbose_name_plural': 'Purchase Report Data',
            },
        ),
    ]
