# Generated by Django 2.2.17 on 2021-02-02 11:46

from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import givesome.models.vendor_extra


class Migration(migrations.Migration):

    dependencies = [
        ('shuup', '0082_add_name_to_shop_product'),
        ('givesome', '0026_purchasereportdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='givesomeoffice',
            name='primary_project',
            field=models.ForeignKey(blank=True, help_text='Selected project will be prioritized when automatically reallocating expiring Givecard funds.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_offices', to='shuup.ShopProduct', verbose_name='Primary project'),
        ),
        migrations.AddField(
            model_name='vendorextra',
            name='primary_project',
            field=models.ForeignKey(blank=True, help_text='Selected project will be prioritized when automatically reallocating expiring Givecard funds.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_suppliers', to='shuup.ShopProduct', verbose_name='Primary project'),
        ),
        migrations.AlterField(
            model_name='vendorextra',
            name='vendor_type',
            field=enumfields.fields.EnumIntegerField(default=1, enum=givesome.models.vendor_extra.VendorExtraType, help_text='Charities may sign up as charities in order to create charity projects. They may pay to upgrade to Branded Vendor status if they wish, which will enable them to feature their projects on their Branded Vendor Page.', verbose_name='vendor type'),
        ),
        migrations.AlterField(
            model_name='vendorextra',
            name='website_url',
            field=models.CharField(blank=True, help_text="Enter the URL of the vendor's website.", max_length=128, null=True, verbose_name='URL'),
        ),
    ]
