# Generated by Django 2.2.17 on 2021-02-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('givesome', '0027_add_primary_project_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='givecard',
            name='was_automatically_donated',
        ),
        migrations.AddField(
            model_name='givecard',
            name='automatically_donated',
            field=models.PositiveIntegerField(default=0, help_text='Balance ($) from this givecard that was donated automatically', verbose_name='automatically donated amount'),
        ),
    ]
