# Generated by Django 2.2.17 on 2021-02-16 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shuup', '0082_add_name_to_shop_product'),
        ('givesome', '0028_givecard_automatically_donated'),
    ]

    operations = [
        migrations.CreateModel(
            name='GivesomePurse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.PositiveIntegerField(help_text='Balance ($) left in the Givesome Purse', verbose_name='balance')),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='givesome_purse', to='shuup.Shop', verbose_name='shop')),
            ],
            options={
                'verbose_name': 'givesome purse',
                'verbose_name_plural': 'givesome purses',
            },
        ),
    ]
