# Generated by Django 2.2.17 on 2021-02-16 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shuup', '0082_add_name_to_shop_product'),
        ('givesome', '0029_givesome_purse'),
    ]

    operations = [
        migrations.CreateModel(
            name='GivesomePurseAllocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveIntegerField(default=0, verbose_name='weight')),
                ('purse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='givesome.GivesomePurse')),
                ('shop_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purse_allocations', to='shuup.ShopProduct')),
            ],
            options={
                'verbose_name': 'givesome purse allocation',
                'verbose_name_plural': 'givesome purse allocations',
            },
        ),
    ]
