# Generated by Django 2.2.17 on 2021-02-22 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shuup', '0082_add_name_to_shop_product'),
        ('givesome', '0030_givesome_purse_allocations'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.DecimalField(decimal_places=2, help_text='How many hours did you volunteer?', max_digits=5)),
                ('volunteered_on', models.DateField(help_text='When did you volunteer?')),
                ('description', models.CharField(help_text='Who did you help?', max_length=68)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='volunteer_hours', to='shuup.PersonContact')),
            ],
        ),
        migrations.CreateModel(
            name='OffPlatformDonation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='How much did you donate?', max_digits=5)),
                ('donated_on', models.DateField(help_text='When did you donate?')),
                ('description', models.CharField(help_text='Who did you help?', max_length=68)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='off_platform_donations', to='shuup.PersonContact')),
            ],
        ),
    ]
