# Generated by Django 2.2.17 on 2021-02-25 13:23

from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import givesome.models.reports


class Migration(migrations.Migration):

    dependencies = [
        ('shuup', '0082_add_name_to_shop_product'),
        ('givesome', '0033_update_purchase_report_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='GivesomeDonationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_type', enumfields.fields.EnumIntegerField(enum=givesome.models.reports.GivesomeDonationType, verbose_name='Donation Type')),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='givesome_donation_data', to='givesome.GivecardBatch', verbose_name='Givecard Batch')),
                ('givesome_purse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='givesome_donation_data', to='givesome.GivesomePurse', verbose_name='Givesome Purse')),
                ('office', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='givesome_donation_data', to='givesome.GivesomeOffice', verbose_name='Office')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='givesome_donation_data', to='shuup.Payment', verbose_name='Payment')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='givesome_donation_data', to='shuup.Supplier', verbose_name='Supplier')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GivecardPurseCharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_date', models.DateTimeField(editable=False, verbose_name='Charge date')),
                ('charge_amount', models.PositiveIntegerField(help_text='Amount of balance transferred from the Givecard Batch to Givesome Purse', verbose_name='Charge amount')),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='givesome_purse_charge', to='givesome.GivecardBatch', verbose_name='Givesome Purse Charge')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
