# Generated by Django 2.2.17 on 2021-03-01 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shuup', '0082_add_name_to_shop_product'),
        ('givesome', '0034_expiry_donation_logging'),
    ]

    operations = [
        migrations.CreateModel(
            name='NullifiedGivecardBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('nullified_on', models.DateField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='givesome.GivecardBatch')),
                ('nullified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shuup.PersonContact')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
