# Generated by Django 2.2.17 on 2021-03-08 16:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('givesome', '0036_batch_changes'),
    ]

    operations = [
        migrations.AddField(
            model_name='givecardcampaign',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created on'),
            preserve_default=False,
        ),
    ]
