# Generated by Django 2.2.17 on 2021-03-08 20:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import givesome.models.givecard


class Migration(migrations.Migration):

    dependencies = [
        ('shuup', '0084_tracking_url'),
        ('givesome', '0037_campaign_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='givesomepromotedproduct',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promoted_projects', to='shuup.Supplier'),
        ),
        migrations.AlterField(
            model_name='givecard',
            name='code',
            field=models.CharField(blank=True, help_text='Used for givecard redemption.', max_length=6, null=True, verbose_name='PIN'),
        ),
        migrations.AlterField(
            model_name='givecardbatch',
            name='amount',
            field=models.PositiveIntegerField(default=1, help_text='Quantity of Givecards to generate in this batch.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100000)], verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='givecardbatch',
            name='code',
            field=models.CharField(blank=True, help_text='Used for givecard redemption. Required for Multicards. This code will be the same for all Multicards in this batch.', max_length=6, null=True, verbose_name='PIN'),
        ),
        migrations.AlterField(
            model_name='givecardbatch',
            name='restriction_type',
            field=enumfields.fields.EnumIntegerField(default=1, enum=givesome.models.givecard.GivecardDonateRestrictionType, help_text="Defines how Givecards are allowed to be donated. Office - Givecards can only be used on this Office's branded page. Supplier - Givecards can only be used on vendor's and it's office's branded pages. Disabled - No donation restrictions.", verbose_name='Donation restriction type'),
        ),
        migrations.AlterField(
            model_name='givesomepromotedproduct',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promoted_projects', to='givesome.GivesomeOffice'),
        ),
        migrations.AlterField(
            model_name='givesomepromotedproduct',
            name='shop_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='shuup.ShopProduct'),
        ),
    ]
