# Generated by Django 2.2.17 on 2021-04-01 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('givesome', '0038_supplier_to_promoted_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorextra',
            name='ordering',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='offplatformdonation',
            name='description',
            field=models.CharField(help_text='Who did you help?', max_length=68, verbose_name='Where did you give to?'),
        ),
        migrations.AlterField(
            model_name='volunteerhours',
            name='description',
            field=models.CharField(help_text='Who did you help?', max_length=68, verbose_name='Where did you volunteer?'),
        ),
    ]
