# Generated by Django 2.2.17 on 2021-04-06 13:32

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shuup', '0084_tracking_url'),
        ('givesome', '0039_add_vendor_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectextra',
            name='sponsored_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sponsored_projects', to='shuup.Supplier', verbose_name='Sponsored by'),
        ),
        migrations.AddField(
            model_name='vendorextra',
            name='sponsored_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sponsored_charities', to='shuup.Supplier', verbose_name='Sponsored by'),
        ),
        migrations.AlterField(
            model_name='offplatformdonation',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='How much did you donate?', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='volunteerhours',
            name='hours',
            field=models.DecimalField(decimal_places=2, help_text='How many hours did you volunteer?', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
