# Generated by Django 2.2.17 on 2021-04-09 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('givesome', '0041_projectextra_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectextra',
            name='featured',
        ),
        migrations.AddField(
            model_name='projectextra',
            name='featured_project',
            field=models.BooleanField(default=False, help_text='Feature this project on the homepage "Featured Projects" carousel.'),
        ),
        migrations.AddField(
            model_name='projectextra',
            name='featured_project_order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectextra',
            name='featured_video',
            field=models.BooleanField(default=False, help_text="Feature this project's video on the home page. Projects must have a video."),
        ),
    ]
