# Generated by Django 2.2.21 on 2021-06-15 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('givesome', '0043_add_description_field_to_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='givesomepurse',
            name='balance',
        ),
    ]
