# Generated by Django 2.2.21 on 2021-06-21 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('givesome', '0044_move_purse_balance_to_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='givecardbatch',
            name='archived',
            field=models.BooleanField(default=False, help_text='Archived Givecard Batches are excluded on Vendor dashboards.', verbose_name='Archived'),
        ),
        migrations.AddField(
            model_name='givecardcampaign',
            name='archived',
            field=models.BooleanField(default=False, help_text='Archived Givecard Campaigns are hidden on Vendor dashboards.', verbose_name='Archived'),
        ),
    ]
