# Generated by Django 2.2.21 on 2021-07-05 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('givesome', '0046_add_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectextra',
            name='featured_project',
        ),
        migrations.RemoveField(
            model_name='projectextra',
            name='featured_project_order',
        ),
        migrations.RemoveField(
            model_name='projectextra',
            name='featured_video',
        ),
    ]
