# Generated by Django 2.2.21 on 2021-07-07 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('givesome', '0047_remove_featured_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectextra',
            name='available_from',
            field=models.DateTimeField(blank=True, db_index=True, help_text='After this date the project will be visible in the store front.', null=True, verbose_name='Available from date'),
        ),
    ]
