# Generated by Django 2.2.21 on 2021-07-12 13:55

import django.db.models.deletion
import mptt.fields
from django.db import migrations
from django.db import models
from mptt import register, managers


def rebuild_tree(apps, schema_editor):
    GivesomeOffice = apps.get_model('givesome', 'GivesomeOffice')

    manager = managers.TreeManager()
    manager.model = GivesomeOffice

    register(GivesomeOffice)

    manager.contribute_to_class(GivesomeOffice, 'objects')
    manager.rebuild()


class Migration(migrations.Migration):
    dependencies = [
        ('givesome', '0048_add_available_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='givesomeoffice',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, help_text='If your office is a sub-office of another office, you can link them here.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='givesome.GivesomeOffice', verbose_name='Parent office'),
        ),
        migrations.AddField(
            model_name='givesomeoffice',
            name='level',
            field=models.PositiveIntegerField(db_index=True, editable=False, null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='givesomeoffice',
            name='lft',
            field=models.PositiveIntegerField(db_index=True, editable=False, null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='givesomeoffice',
            name='rght',
            field=models.PositiveIntegerField(db_index=True, editable=False, null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='givesomeoffice',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, editable=False, null=True),
            preserve_default=False,
        ),
        migrations.RunPython(
            rebuild_tree
        )
    ]
