# Generated by Django 2.2.21 on 2021-07-13 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('givesome', '0051_office_term_levels'),
    ]

    operations = [
        migrations.AddField(
            model_name='givesomeoffice',
            name='disabled',
            field=models.BooleanField(default=False, help_text='Disable this office. This office will not be show in the front for customers anymore. All children offices are affected as well. Any related Givecard restrictions will be left unaffected, which means that if any Batches are restricted to this Office or any child offices, it will be impossible to use any of those Givecards.'),
        ),
    ]
