# Generated by Django 2.2.21 on 2021-07-19 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shuup', '0091_background_tasks'),
        ('givesome', '0053_add_redirect_office'),
    ]

    operations = [
        migrations.AddField(
            model_name='givecardpursecharge',
            name='givesome_purse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='purse_charges', to='givesome.GivesomePurse', verbose_name='Givesome Purse'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='givesomepurse',
            name='supplier',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='givesome_purse', to='shuup.Supplier', verbose_name='supplier'),
        ),
        migrations.AlterField(
            model_name='givesomepurse',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='givesome_purse', to='shuup.Shop', verbose_name='shop'),
        ),
    ]
