# Generated by Django 2.2.24 on 2021-09-01 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('givesome', '0057_change_max_digits'),
    ]

    operations = [
        migrations.CreateModel(
            name='GivesomeGif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('gif', filer.fields.image.FilerImageField(blank=True, help_text='Gif that can be displayed on the checkout competion.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL, verbose_name='gif')),
            ],
        ),
    ]
