# Generated by Django 2.2.24 on 2021-08-05 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('givesome', '0058_add_checkout_gif'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='givesomeoffice',
            options={'ordering': ('supplier', 'level', 'ordering')},
        ),
        migrations.AddField(
            model_name='vendorextra',
            name='registration_number',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
