# Generated by Django 2.2.24 on 2021-09-27 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('givesome', '0063_projectextra_enable_receipting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorextra',
            name='registration_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
