# Generated by Django 2.2.24 on 2021-11-29 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('givesome', '0066_donationextra'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptingmessagestranslation',
            name='sign_in_header',
            field=models.TextField(default='', help_text='The title seen by an unregistered user if signing up during the receipting process.'),
        ),
        migrations.AddField(
            model_name='receiptingmessagestranslation',
            name='sign_in_step_1',
            field=models.TextField(default='', help_text='List the first step the user should follow after logging in.'),
        ),
        migrations.AddField(
            model_name='receiptingmessagestranslation',
            name='sign_in_step_2',
            field=models.TextField(default='', help_text='List the second step the user should follow after logging in.'),
        ),
        migrations.AddField(
            model_name='receiptingmessagestranslation',
            name='sign_in_step_3',
            field=models.TextField(default='', help_text='List the third step the user should follow after logging in.'),
        ),
    ]
