# Generated by Django 2.2.24 on 2021-12-23 21:57

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('givesome', '0067_add_receipting_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offplatformdonation',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='How much did you donate?', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='offplatformdonation',
            name='donated_on',
            field=models.DateField(help_text='When did you donate?', verbose_name='Donated on'),
        ),
        migrations.AlterField(
            model_name='volunteerhours',
            name='hours',
            field=models.DecimalField(decimal_places=2, help_text='How many hours did you volunteer?', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Hours'),
        ),
        migrations.AlterField(
            model_name='volunteerhours',
            name='volunteered_on',
            field=models.DateField(help_text='When did you volunteer?', verbose_name='Volunteered on'),
        ),
        migrations.AddField(
            model_name='projectextra',
            name='after_donation_url',
            field=models.URLField(blank=True, help_text='The URL to redirect donors to after a successful donation to this project.', null=True, verbose_name='Donation Redirect URL'),
        ),
    ]
