# Generated by Django 2.2.24 on 2022-01-14 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('givesome', '0068_add_after_donation_redirect_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectextra',
            name='after_donation_url',
        ),
        migrations.AddField(
            model_name='projectextra',
            name='donation_url',
            field=models.URLField(blank=True, help_text='The URL to redirect donors to make a donation to this project.', null=True, verbose_name='Donation URL'),
        ),
    ]
