# Generated by Django 2.2.24 on 2022-08-18 21:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('givesome', '0070_givesomecompetition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='givesomecompetition',
            name='competitors',
            field=models.ManyToManyField(blank=True, help_text='Add competitors here (competitors can also join if you give them the key / link to the competition)', related_name='competitors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vendorextra',
            name='registration_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
