# Generated by Django 2.2.24 on 2022-08-25 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('givesome', '0071_auto_20220818_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorextra',
            name='sponsor_link',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
