# -*- coding: utf-8 -*-
# This file is part of Shuup.
#
# Copyright (c) 2012-2021, Shuup Commerce Inc. All rights reserved.
#
# This source code is licensed under the Shuup Commerce Inc -
# SELF HOSTED SOFTWARE LICENSE AGREEMENT executed by Shuup Commerce Inc, DBA as SHUUP®
# and the Licensee.

import random
import string


def get_all_existing_codes() -> set:
    """Returns a set of all Givecard codes currently in use"""
    from givesome.models import Givecard, GivecardBatch

    multicard_codes = GivecardBatch.objects.exclude(code__isnull=True).values_list("code", flat=True)
    givecard_codes = Givecard.objects.exclude(code__isnull=True).values_list("code", flat=True)
    return set(list(multicard_codes) + list(givecard_codes))


# noinspection SpellCheckingInspection
def has_bad_words(code: str) -> bool:
    """Matches given code to words with a "good enough" degree of certainty"""
    bad_words = [
        "AEOLUS",
        "AHOLE",
        "ANAL",
        "ANUS",
        "ARIAN",
        "ARSE",
        "ARYAN",
        "ASS",
        "AZZ",
        "BABE",
        "BALL",
        "BANG",
        "BARF",
        "BAWDY",
        "BIATCH",
        "BIMBO",
        "BITCH",
        "BLOODY",
        "BLOW",
        "BONE",
        "BOOB",
        "BREAST",
        "BUGGER",
        "BUKAKE",
        "BUM",
        "BUNG",
        "BUSTY",
        "BUTAKE",
        "BUTT",
        "CACA",
        "CAHONE",
        "CHOADE",
        "CHODE",
        "CLIT",
        "COCK",
        "COK",
        "CONDOM",
        "COX",
        "CRAP",
        "CUM",
        "CUNNY",
        "CUNT",
        "DAMMIT",
        "DAMN",
        "DICK",
        "DIKE",
        "DILDO",
        "DOGGIE",
        "DONG",
        "ERECT",
        "EROTIC",
        "FAG",
        "FCK",
        "FCUK",
        "FECK",
        "FELCH",
        "FELTCH",
        "FIST",
        "FUCK",
        "FUK",
        "GANG",
        "GAY",
        "GOD",
        "HELL",
        "HEMP",
        "HEROIN",
        "HERPES",
        "HITLER",
        "HIV",
        "HOAR",
        "HOMO",
        "HOOK",
        "HORNY",
        "HUMP",
        "HYMEN",
        "INBRED",
        "INCEST",
        "JACK",
        "JERK",
        "JIZ",
        "KILL",
        "KINK",
        "KOOCH",
        "KUM",
        "LESB",
        "LEZ",
        "LMFAO",
        "LOIN",
        "LUBE",
        "LUST",
        "MASTER",
        "MASTR",
        "MAXI",
        "MENSES",
        "METH",
        "MOFO",
        "MOOLIE",
        "MORON",
        "MURDER",
        "MUTHA",
        "NAD",
        "NAKED",
        "NAPALM",
        "NAZI",
        "NEGRO",
        "NIGGA",
        "NIGGER",
        "NIGGLE",
        "NIGLET",
        "NIPPLE",
        "NOB",
        "NUT",
        "OMG",
        "OPIATE",
        "OPIUM",
        "ORAL",
        "ORGASM",
        "ORGIES",
        "ORGY",
        "PANTIE",
        "PANTY",
        "PASTIE",
        "PASTY",
        "PECKER",
        "PEDO",
        "PEE",
        "PENIAL",
        "PENILE",
        "PENIS",
        "PHUCK",
        "PHUK",
        "PHUQ",
        "PIMP",
        "PISS",
        "PMS",
        "POLACK",
        "POON",
        "POOP",
        "PORN",
        "POT",
        "POUND",
        "PRICK",
        "PRIG",
        "PRON",
        "PRUDE",
        "PUBE",
        "PUBIC",
        "PUBIS",
        "PUNT",
        "PUSS",
        "QUEAF",
        "QUEEF",
        "QUEER",
        "RACY",
        "RAPE",
        "RAPIST",
        "RAUNCH",
        "RECTAL",
        "RECTUM",
        "RECTUS",
        "REEFER",
        "RIM",
        "RUMP",
        "SCAG",
        "SCANT",
        "SCHIZO",
        "SCREW",
        "SCROAT",
        "SEDUCE",
        "SEMEN",
        "SEX",
        "SHAG",
        "SHIT",
        "SKAG",
        "SKANK",
        "SLAVE",
        "SLEAZE",
        "SLEAZY",
        "SLUT",
        "SMUT",
        "SNUFF",
        "SOB",
        "SODOM",
        "SPERM",
        "SPIC",
        "SPIK",
        "STEAMY",
        "STFU",
        "STONE",
        "STRIP",
        "STROKE",
        "STUPID",
        "SUCK",
        "TARD",
        "TAWDRY",
        "TEABAG",
        "TESTES",
        "TESTIS",
        "THRUST",
        "TIT",
        "TRAMP",
        "TRANS",
        "TURD",
        "TUSH",
        "TWAT",
        "UGLY",
        "UNDIES",
        "URINAL",
        "URINE",
        "VAG",
        "VALIUM",
        "VIAGRA",
        "VIRGIN",
        "VIXEN",
        "VODKA",
        "VOMIT",
        "VOYEUR",
        "VULGAR",
        "VULVA",
        "WAD",
        "WANG",
        "WANK",
        "WEED",
        "WEINER",
        "WEIRDO",
        "WENCH",
        "WHORE",
        "WIGGER",
        "WILLY",
        "WOOD",
        "WOP",
        "WTF",
        "XXX",
    ]
    for word in bad_words:
        if word in code:
            return True
    return False


def generate_new_codes(amount: int) -> set:
    """Returns a set of n-amount of of available codes"""
    old_codes = get_all_existing_codes()
    new_codes = set()
    allowed_characters = string.ascii_uppercase
    while len(new_codes) < amount:
        code = "".join(random.choices(allowed_characters, k=6))
        if code not in old_codes:
            if not has_bad_words(code):
                new_codes.add(code)
    return new_codes


def generate_new_code() -> string:
    """Returns a random new code"""
    return list(generate_new_codes(1))[0]
